### PR TITLE
Added new unary ops, including tanh, sin, cos, and sign. 

### PR DESCRIPTION
**Pull request by chaseadams509**
Also corrected floor/ceil unary ops to call the correct nGraph function.

### CODE REVIEW

**Comment by avijit-nervana** [comment]
Did you not have to modify run-unit-tests.sh to add the tests for the new ops?

**Comment by chaseadams509** [comment]
Actually, might be best to have the added tests in this PR, now that I think of it. That way, it avoids having one PR depend on another.

**Comment by chaseadams509** [comment]
Good idea! There are a few that I do not know why, but I can comment as such.

**Comment by avijit-nervana** [comment]
TESTNOW

**Comment by avijit-nervana** [comment]
TESTNOW

**Comment by chaseadams509** [comment]
TESTNOW

**Comment by chaseadams509** [comment]
TESTNOW

**Pull request merged**
